name: insta_like_button
description: Instagram post style customizable card widget made for flutter
version: 0.1.1 
homepage: https://github.com/theiskaa/insta-like-button

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - example/overview/img.jpg
